services:
  - type: web
    name: socketasynmessagen
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production

  - type: keyvalue
    name: socketasynmessagen-redis
    plan: free
    region: oregon
    ipAllowList: []
